### ISSUE TITLE
Crash on no such method

### ISSUE THREAD

**Issue by Zethalion** [Wealthyturtle/Additional-Compression#1]
See this log: https://gist.github.com/anonymous/dc19fc15e3938a0a7411b5fbe2caaddb

**Comment by RCXcrafter** [comment]
Upgrading to [this version](https://minecraft.curseforge.com/projects/crafttweaker) of minetweaker should fix that. Or is that not an option for you?

**Comment by Zethalion** [comment]
Thanks for the reply. I tried that one right away. However, it failed me too. No regular crash report. Took from the fml-server-latest.log https://gist.github.com/Zethalion/4307175a9973eba849de952e12ec8be1

"UCHIJAE	MineTweaker3{3.0.13} [MineTweaker 3] (CraftTweaker-1.7.10-3.0.13.jar) "

**Comment by Zethalion** [comment]
It seems incompatible with MineTweakerRecipeMaker. I'll just need to loose that mod.

[edit] Got your mod working. Compressed fish! XD Love it!

**Comment by RCXcrafter** [comment]
Thanks, also updating MineTweakerRecipeMaker would probably fix that error since the version you're using seems to come all the way from 2014.

**Comment by Zethalion** [comment]
I know. It was the latest for 1.7.10 on curse for a very long time. Now you mentioned it, I saw it has been updated recently after no new release in almost 3 years! Who would've expected that?

Thanks for the hints!
