### ISSUE TITLE
icon for 'Block of String' #4471 is not displaying in mc

### ISSUE THREAD

**Issue by markygnlg** [Wealthyturtle/Additional-Compression#14]
I'm using mc 1.12.2 with Additional-Compression-1.12.2-3.4.jar
It works fine but the icon does not display.

![image](https://user-images.githubusercontent.com/62978705/82148897-32052080-9894-11ea-9098-74a93ee35c16.png)

**Comment by ferreiraalex** [comment]
add this to blockstates folder in mod
https://dl.uploadgram.me/6105f94282017h
it fix your needs

**Comment by markygnlg** [comment]
['Close as not planned: Wont fix, can't repro, duplicate, stale']
