### ISSUE TITLE
BlockCompressed doesn't use passed in parameter in getPickBlock

### ISSUE THREAD

**Issue by ichttt** [Wealthyturtle/Additional-Compression#3]
Hi,
your mod currently fetches the blockstate from [the world directly instead of using the parameter passed ](https://github.com/Wealthyturtle/Additional-Compression/blob/eeae1c7c3f768f70c4440aec2fd5c31071f52d7b/src/main/java/com/wealthyturtle/additionalcompression/blocks/BlockCompressed.java#L61)in by the method. I don't see any reasons for this, but [it breaks my mod](https://paste.dimdev.org/wizowobawu.php)
Please change it to use the IBlockState passed in by the method.

**Comment by RCXcrafter** [comment]
That must be left there from porting the mod, this will be fixed in the next version.
