### ISSUE TITLE
I can not compress sand

### ISSUE THREAD

**Issue by karikusa** [Wealthyturtle/Additional-Compression#6]
Thanks! 
Probably it seems that the recipe is wrong so I will report it.
A recipe for making sand compressed from sand consists only of compressed sand,
It is in a state where compression at the first step can not be done.
Verification please!

**Comment by Nightstalker36** [comment]
Yes, it is the recipe. I have the latest version of Additional Compression, and sand still can't be compressed.
The recipe in JEI calls for 9 single compressed sand to make 1 single compressed sand. I've been using Additional Compression for about a year or so, and I only just discovered the recipe mistake. Initially I just thought all sand couldn't be compressed, but Red Sand recipe is correct. 9 red sand = single compressed red sand.
